### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by dohliam** [darshandsoni/jalibut#6]
There should probably be some mention in the readme about the fact that jalibut supports searching with regular expressions out of the box. This is particularly helpful with large collections.

For example, try searching [here](https://dohliam.github.io/libreoffice-impress-templates/) for the string `fedora.*grey` to see everything in the fedora category that also mentions the word "grey". I discovered this by accident. :smile: 

This makes jalibut incredibly powerful as a tool for searching/organizing information, and more people should know about it! A note somewhere in the showcase about supporting regex with a link to an overview of regular expression syntax would be great too.

**Comment by darshandsoni** [comment]
In full accordance, a section has been added to the readme. The default search bar also shows that regex is supported.
